#!/usr/bin/env ruby -I day_05
require 'naughty_strings'

# Read input split into lines
all_strings = ARGF.read.split(/\n/).reject(&:empty?)

# Select only the nice strings
nice_strings = all_strings.select { |x| NaughtyStrings.nice_string(x) }

puts "#{nice_strings.length} nice strings found"

# Select only the NICER strings
nicer_strings = all_strings.select { |x| NaughtyStrings.nicer_string(x) }

puts "#{nicer_strings.length} NICER strings found"
