#!/usr/bin/env python3
import sys
from present_path import PresentPath

path = PresentPath(sys.stdin)
print("The shortest route is:", path.shortest)
print(' -> '.join(path.shortest_route))
print("The longest route is:", path.longest)
print(' -> '.join(path.longest_route))
