#!/usr/bin/env python3

import sys

MATCH_CONDITIONS = [
    'children: 3',
    'cats: 7',
    'samoyeds: 2',
    'pomeranians: 3',
    'akitas: 0',
    'vizslas: 0',
    'goldfish: 5',
    'trees: 3',
    'cars: 2',
    'perfumes: 1'
]

for line in sys.stdin:
    for cond in MATCH_CONDITIONS:
        if cond in line:
            line = line.replace(cond, '')
    line = line.replace(', ', '')
    if len(line) < len('Sue 123: ..'):
        print(line)
